<a href="https://colab.research.google.com/github/25pa1a45c8/Nasscom_Lab/blob/main/Pandas_lab2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
pd.read_csv("filename.csv")

In [ ]:
#df.head()  # to show the rows
#df.tail() # to show the records from back
#df.dtypes() # eg: int64
#df.shape()
#df.info() # gives no. of rows & col and no. of non-null values and datatype
#df.describe # count,mean,min,max,std(standard deviations).only numerical data it does manipilations

In [ ]:
import pandas as pd
marks = pd.Series([80,94,79,57,29])
marks

0    80
1    94
2    79
3    57
4    29
dtype: int64

In [ ]:
print("First value: ",marks[0])
print("Third value: ",marks[2])

First value:  80
Third value:  79

In [ ]:
#create a panda series containing the marks of6 students and print the third student marks
marks = pd.Series([89,30,59,94,75])
print("Third student marks: ",marks[2])

Third student marks:  59

In [ ]:
data = {"Name" : ["Lasya","Afrin","Lochana"],"Marks" : [59,64,83],"Attendance" : [87,79,73]}
s = pd.DataFrame(data)
print(s)

      Name  Marks  Attendance
0    Lasya     59          87
1    Afrin     64          79
2  Lochana     83          73

In [8]:
student_data = {
    "Student": ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10",
                "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19", "S20"],
    "Study_Hours": [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 1, 2, 4, 6],
    "Attendance": [55, 94, 65, 68, 72, 70, 75, 78, 52, 80, 85, 88, 90, 66, 92, 90, 80, 58, 62, 75],
    "Assignments": [9, 1, 4, 5, 6, 6, 9, 7, 8, 8, 9, 9, 10, 10,8, 10, 1, 2, 5, 7],
    "Previous_Marks": [38, 42, 45, 48, 52, 55, 58, 61, 64, 66, 70, 73, 76, 78, 82, 85, 35, 40, 50, 68],
    "Final_Result": ["Fail", "Fail", "Fail", "Fail", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass",
                     "Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Fail", "Fail", "Fail", "Pass"]
}
student= pd.DataFrame(student_data)
print(student)

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0       S1            1          55            9              38         Fail
1       S2            2          94            1              42         Fail
2       S3            2          65            4              45         Fail
3       S4            3          68            5              48         Fail
4       S5            3          72            6              52         Pass
5       S6            4          70            6              55         Pass
6       S7            4          75            9              58         Pass
7       S8            5          78            7              61         Pass
8       S9            5          52            8              64         Pass
9      S10            6          80            8              66         Pass
10     S11            6          85            9              70         Pass
11     S12            7          88            9              73         Pass
12     S13            7          90           10              76         Pass
13     S14            8          66           10              78         Pass
14     S15            8          92            8              82         Pass
15     S16            9          90           10              85         Pass
16     S17            1          80            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            7              68         Pass

In [15]:
student.to_csv("student.csv",index = False)
print("students.csv created successfully")

students.csv created successfully

In [17]:
df = pd.read_csv("student.csv")
df

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0       S1            1          55            9              38         Fail
1       S2            2          94            1              42         Fail
2       S3            2          65            4              45         Fail
3       S4            3          68            5              48         Fail
4       S5            3          72            6              52         Pass
5       S6            4          70            6              55         Pass
6       S7            4          75            9              58         Pass
7       S8            5          78            7              61         Pass
8       S9            5          52            8              64         Pass
9      S10            6          80            8              66         Pass
10     S11            6          85            9              70         Pass
11     S12            7          88            9              73         Pass
12     S13            7          90           10              76         Pass
13     S14            8          66           10              78         Pass
14     S15            8          92            8              82         Pass
15     S16            9          90           10              85         Pass
16     S17            1          80            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            7              68         Pass

In [11]:
df.head(5)

  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            9              38         Fail
1      S2            2          94            1              42         Fail
2      S3            2          65            4              45         Fail
3      S4            3          68            5              48         Fail
4      S5            3          72            6              52         Pass

In [12]:
df.tail(5)

   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
15     S16            9          90           10              85         Pass
16     S17            1          80            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            7              68         Pass

In [19]:
import pandas as pd
df = pd.read_csv("student.csv")
df.shape

(20, 6)

In [20]:
df.columns

Index(['Student', 'Study_Hours', 'Attendance', 'Assignments', 'Previous_Marks',
       'Final_Result'],
      dtype='object')

In [21]:
df.columns.tolist()

['Student',
 'Study_Hours',
 'Attendance',
 'Assignments',
 'Previous_Marks',
 'Final_Result']

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student         20 non-null     object
 1   Study_Hours     20 non-null     int64
 2   Attendance      20 non-null     int64
 3   Assignments     20 non-null     int64
 4   Previous_Marks  20 non-null     int64
 5   Final_Result    20 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.1+ KB

In [26]:
df.describe()

       Study_Hours  Attendance  Assignments  Previous_Marks
count    20.000000   20.000000    20.000000       20.000000
mean      4.650000   74.750000     6.700000       59.300000
std       2.433862   12.727405     2.903718       15.321468
min       1.000000   52.000000     1.000000       35.000000
25%       2.750000   65.750000     5.000000       47.250000
50%       4.500000   75.000000     7.500000       59.500000
75%       6.250000   85.750000     9.000000       70.750000
max       9.000000   94.000000    10.000000       85.000000

## 🧠 Mini Practice Set

Try these without looking at the previous cells.

### Question 1
Display only the `Attendance` column.

### Question 2
Display `Student` and `Final_Result`.

### Question 3
Display the first 10 rows.

### Question 4
Find the number of rows and columns.

### Question 5
Display the data types of all columns.

In [37]:
df["Attendance"]

0     55
1     94
2     65
3     68
4     72
5     70
6     75
7     78
8     52
9     80
10    85
11    88
12    90
13    66
14    92
15    90
16    80
17    58
18    62
19    75
Name: Attendance, dtype: int64

In [32]:
df[["Attendance","Assignments","Study_Hours"]]

    Attendance  Assignments  Study_Hours
0           55            9            1
1           94            1            2
2           65            4            2
3           68            5            3
4           72            6            3
5           70            6            4
6           75            9            4
7           78            7            5
8           52            8            5
9           80            8            6
10          85            9            6
11          88            9            7
12          90           10            7
13          66           10            8
14          92            8            8
15          90           10            9
16          80            1            1
17          58            2            2
18          62            5            4
19          75            7            6

In [33]:
df[["Student","Final_Result"]]

   Student Final_Result
0       S1         Fail
1       S2         Fail
2       S3         Fail
3       S4         Fail
4       S5         Pass
5       S6         Pass
6       S7         Pass
7       S8         Pass
8       S9         Pass
9      S10         Pass
10     S11         Pass
11     S12         Pass
12     S13         Pass
13     S14         Pass
14     S15         Pass
15     S16         Pass
16     S17         Fail
17     S18         Fail
18     S19         Fail
19     S20         Pass

In [34]:
df.head(10)

  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            9              38         Fail
1      S2            2          94            1              42         Fail
2      S3            2          65            4              45         Fail
3      S4            3          68            5              48         Fail
4      S5            3          72            6              52         Pass
5      S6            4          70            6              55         Pass
6      S7            4          75            9              58         Pass
7      S8            5          78            7              61         Pass
8      S9            5          52            8              64         Pass
9     S10            6          80            8              66         Pass

In [38]:
df.shape

(20, 6)

In [39]:
df.dtypes

Student           object
Study_Hours        int64
Attendance         int64
Assignments        int64
Previous_Marks     int64
Final_Result      object
dtype: object

## 🎯 Lab Challenge

Without changing the original dataset, answer these questions using Pandas:

1. How many students are present in the dataset?
2. How many features/columns are present?
3. What are the column names?
4. Display the first 7 students.
5. Display the last 4 students.
6. Display only `Study_Hours` and `Final_Result`.
7. Display `Attendance`, `Previous_Marks`, and `Final_Result`.
8. Display the statistical summary of the numerical columns.
9. Check the data types of all columns.
10. Display the complete information about the dataset using `info()`.

In [42]:
print("Number of Students : ",len(df))

Number of Students :  20

In [43]:
print("Number of Columns : ",len(df.columns))

Number of Columns :  6

In [47]:
print("Columns are : ",df.columns.tolist())

Columns are :  ['Student', 'Study_Hours', 'Attendance', 'Assignments', 'Previous_Marks', 'Final_Result']

In [51]:
print("The first 7 students are : ")
print(df.head(7))

The first 7 students are :
  Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
0      S1            1          55            9              38         Fail
1      S2            2          94            1              42         Fail
2      S3            2          65            4              45         Fail
3      S4            3          68            5              48         Fail
4      S5            3          72            6              52         Pass
5      S6            4          70            6              55         Pass
6      S7            4          75            9              58         Pass

In [52]:
print("The last 4 students are :")
print(df.tail(4))

The last 4 students are :
   Student  Study_Hours  Attendance  Assignments  Previous_Marks Final_Result
16     S17            1          80            1              35         Fail
17     S18            2          58            2              40         Fail
18     S19            4          62            5              50         Fail
19     S20            6          75            7              68         Pass

In [54]:
df[["Study_Hours","Final_Result"]]

    Study_Hours Final_Result
0             1         Fail
1             2         Fail
2             2         Fail
3             3         Fail
4             3         Pass
5             4         Pass
6             4         Pass
7             5         Pass
8             5         Pass
9             6         Pass
10            6         Pass
11            7         Pass
12            7         Pass
13            8         Pass
14            8         Pass
15            9         Pass
16            1         Fail
17            2         Fail
18            4         Fail
19            6         Pass

In [55]:
df[["Attendance","Previous_Marks","Final_Result"]]

    Attendance  Previous_Marks Final_Result
0           55              38         Fail
1           94              42         Fail
2           65              45         Fail
3           68              48         Fail
4           72              52         Pass
5           70              55         Pass
6           75              58         Pass
7           78              61         Pass
8           52              64         Pass
9           80              66         Pass
10          85              70         Pass
11          88              73         Pass
12          90              76         Pass
13          66              78         Pass
14          92              82         Pass
15          90              85         Pass
16          80              35         Fail
17          58              40         Fail
18          62              50         Fail
19          75              68         Pass

In [56]:
df.describe()

       Study_Hours  Attendance  Assignments  Previous_Marks
count    20.000000   20.000000    20.000000       20.000000
mean      4.650000   74.750000     6.700000       59.300000
std       2.433862   12.727405     2.903718       15.321468
min       1.000000   52.000000     1.000000       35.000000
25%       2.750000   65.750000     5.000000       47.250000
50%       4.500000   75.000000     7.500000       59.500000
75%       6.250000   85.750000     9.000000       70.750000
max       9.000000   94.000000    10.000000       85.000000

In [57]:
print(df.dtypes)

Student           object
Study_Hours        int64
Attendance         int64
Assignments        int64
Previous_Marks     int64
Final_Result      object
dtype: object

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student         20 non-null     object
 1   Study_Hours     20 non-null     int64
 2   Attendance      20 non-null     int64
 3   Assignments     20 non-null     int64
 4   Previous_Marks  20 non-null     int64
 5   Final_Result    20 non-null     object
dtypes: int64(4), object(2)
memory usage: 1.1+ KB